-- +goose Up
CREATE SCHEMA "auth";

CREATE SCHEMA "profiles";

CREATE SCHEMA "hrm";

CREATE SCHEMA "crm";

CREATE SCHEMA "nri";

CREATE SCHEMA "tasks";

CREATE TABLE "auth"."Roles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(100) NOT NULL
);

CREATE TABLE "auth"."Permissions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" varchar(100) NOT NULL
);

CREATE TABLE "auth"."RolePermissions" (
  "role_id" integer,
  "permission_id" integer,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "auth"."Accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar(100) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "role_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "auth"."Sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint NOT NULL,
  "access_token_hash" varchar(64) UNIQUE NOT NULL,
  "access_token_expires_at" timestamptz NOT NULL DEFAULT (now() + interval '15 minutes'),
  "refresh_token_hash" varchar(64) UNIQUE NOT NULL,
  "refresh_token_expires_at" timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "last_used_at" timestamptz,
  "revoked_at" timestamptz
);

CREATE TABLE "profiles"."Profiles" (
  "account_id" bigint PRIMARY KEY,
  "full_name" varchar(150) NOT NULL,
  "phone_number" varchar(20) UNIQUE NOT NULL,
  "email" varchar(254) UNIQUE NOT NULL,
  "image" bytea,
  "birth_date" date,
  "position" varchar(100)
);

CREATE TABLE "hrm"."Employees" (
  "account_id" bigint PRIMARY KEY,
  "hire_date" date
);

CREATE TABLE "crm"."Clients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "address" varchar(500) NOT NULL,
  "ceo_id" bigint
);

CREATE TABLE "crm"."Representatives" (
  "account_id" bigint PRIMARY KEY,
  "client_id" bigint NOT NULL
);

CREATE TABLE "crm"."Sites" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsible_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "address" varchar(500) NOT NULL
);

CREATE TABLE "crm"."Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE "crm"."SitesProducts" (
  "site_id" bigint,
  "product_id" integer,
  PRIMARY KEY ("site_id", "product_id")
);

CREATE TABLE "nri"."Equipment_Types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(64) NOT NULL,
  "description" text
);

CREATE TABLE "nri"."ProductEquipment_Types" (
  "product_id" integer,
  "equipment_type_id" integer,
  PRIMARY KEY ("product_id", "equipment_type_id")
);

CREATE TABLE "nri"."Equipment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" integer NOT NULL,
  "site_id" bigint NOT NULL,
  "serial_number" varchar(32),
  "name" varchar(64) NOT NULL,
  "weight" decimal(10,2),
  "description" text
);

CREATE TABLE "tasks"."Type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tasks"."Status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tasks"."Criticality" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "deadline" interval NOT NULL
);

CREATE TABLE "tasks"."Tickets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "type_id" integer NOT NULL,
  "status_id" integer NOT NULL,
  "criticality_id" integer NOT NULL,
  "client_id" bigint NOT NULL,
  "site_id" bigint,
  "product_id" integer,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "created_by" bigint NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_by" bigint NOT NULL,
  "responsible_id" bigint
);

CREATE TABLE "tasks"."ConnectedTickets" (
  "first_task_id" bigint,
  "second_task_id" bigint,
  "relation_type" varchar(20) NOT NULL DEFAULT 'related',
  CHECK (first_task_id < second_task_id),
  PRIMARY KEY ("first_task_id", "second_task_id")
);

CREATE TABLE "tasks"."Comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" bigint NOT NULL,
  "is_closed_comment" bool NOT NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "contents" text NOT NULL
);

CREATE TABLE "tasks"."Reactions" (
  "id" bigint PRIMARY KEY,
  "name" varchar(64) NOT NULL,
  "picture" bytea NOT NULL
);

CREATE TABLE "tasks"."CommentsReactions" (
  "comment_id" bigint,
  "reaction_id" bigint,
  PRIMARY KEY ("comment_id", "reaction_id")
);

CREATE INDEX ON "auth"."Accounts" ("role_id");
CREATE INDEX ON "auth"."Sessions" ("account_id");
CREATE INDEX ON "auth"."Sessions" ("access_token_expires_at", "revoked_at");
CREATE INDEX ON "auth"."Sessions" ("refresh_token_expires_at", "revoked_at");
CREATE INDEX ON "crm"."SitesProducts" ("site_id");
CREATE INDEX ON "tasks"."Tickets" ("title");
CREATE INDEX ON "tasks"."Tickets" ("type_id");
CREATE INDEX ON "tasks"."Tickets" ("status_id");
CREATE INDEX ON "tasks"."Tickets" ("criticality_id");
CREATE INDEX ON "tasks"."Tickets" ("client_id", "created_at");
CREATE INDEX ON "tasks"."Tickets" ("site_id", "created_at");
CREATE INDEX ON "tasks"."Tickets" ("responsible_id", "status_id");
CREATE INDEX ON "tasks"."ConnectedTickets" ("first_task_id");
CREATE INDEX ON "tasks"."ConnectedTickets" ("second_task_id");

COMMENT ON TABLE "auth"."Roles" IS 'Роли, определенные в системе';
COMMENT ON COLUMN "auth"."Roles"."name" IS 'Кодовое имя роли: Роль по умолчанию (без прав), Админ, Оператор КТП, Оператор WFM, Представитель клиента и т.д.';
COMMENT ON COLUMN "auth"."Roles"."description" IS 'Описание роли';
COMMENT ON TABLE "auth"."Permissions" IS 'Права, определенные в системе';
COMMENT ON COLUMN "auth"."Permissions"."name" IS 'Кодовое имя права';
COMMENT ON COLUMN "auth"."Permissions"."description" IS 'Описание права';
COMMENT ON TABLE "auth"."RolePermissions" IS 'Сопоставление ролей и прав';
COMMENT ON TABLE "auth"."Accounts" IS 'Учетные записи пользователей';
COMMENT ON COLUMN "auth"."Accounts"."created_at" IS 'Дата регистрации в системе';
COMMENT ON TABLE "auth"."Sessions" IS 'Открытые сессии пользователей';
COMMENT ON COLUMN "auth"."Sessions"."access_token_hash" IS 'Хеш токена, используемого для авторизации запросов пользователя. Храниться в SHA-256';
COMMENT ON COLUMN "auth"."Sessions"."refresh_token_hash" IS 'Хеш токена, используемого для перевыпуска пары токенов по истечении их времени жизни. Храниться в SHA-256';
COMMENT ON TABLE "profiles"."Profiles" IS 'Профили пользователей системы EBKO_CRM';
COMMENT ON COLUMN "profiles"."Profiles"."full_name" IS 'ФИО пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."phone_number" IS 'Контактный номер пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."email" IS 'Адрес электронной почты пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."image" IS 'Аватарка пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."birth_date" IS 'Дата рождения пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."position" IS 'Должность пользователя';
COMMENT ON TABLE "hrm"."Employees" IS 'Расширение профиля для сотрудников компании, использующей EBKO_CRM';
COMMENT ON COLUMN "hrm"."Employees"."hire_date" IS 'Дата приёма на работу';
COMMENT ON TABLE "crm"."Clients" IS 'Перечень компаний-клиентов';
COMMENT ON COLUMN "crm"."Clients"."name" IS 'Название компании-клиента в системе CRM';
COMMENT ON COLUMN "crm"."Clients"."address" IS 'Адрес головного офиса компании-клиента';
COMMENT ON COLUMN "crm"."Clients"."ceo_id" IS 'СЕО компании-клиента';
COMMENT ON TABLE "crm"."Representatives" IS 'Расширение профиля для представителей компаний-клиентов';
COMMENT ON COLUMN "crm"."Representatives"."client_id" IS 'Компания которую представляет пользователь';
COMMENT ON TABLE "crm"."Sites" IS 'Площадки компаний-клиентов';
COMMENT ON COLUMN "crm"."Sites"."responsible_id" IS 'Ответственный за площадку сотрудник компании-клиента';
COMMENT ON COLUMN "crm"."Sites"."name" IS 'Название площадки компании-клиента';
COMMENT ON COLUMN "crm"."Sites"."address" IS 'Адрес площадки компании-клиента';
COMMENT ON TABLE "crm"."Products" IS 'Продукты предоставляемые компаниям-клиентам';
COMMENT ON COLUMN "crm"."Products"."name" IS 'Название продукта';
COMMENT ON COLUMN "crm"."Products"."description" IS 'Описание продукта';
COMMENT ON TABLE "crm"."SitesProducts" IS 'Сопоставление площадок и продуктов, предоставленных на них';
COMMENT ON TABLE "nri"."Equipment_Types" IS 'Типы единиц оборудования';
COMMENT ON TABLE "nri"."ProductEquipment_Types" IS 'Сопоставление продукта с типом оборудования';
COMMENT ON TABLE "nri"."Equipment" IS 'Оборудование на площадке';
COMMENT ON TABLE "tasks"."Type" IS 'Типы задач создаваемых в системе';
COMMENT ON COLUMN "tasks"."Type"."name" IS 'Название типа задачи: КТП, WFM...';
COMMENT ON TABLE "tasks"."Status" IS 'Статусы задач создаваемых в системе';
COMMENT ON COLUMN "tasks"."Status"."name" IS 'Название статуса задачи: Created, Opened, Active, Canceled, Customer Pending, Done, Verified...';
COMMENT ON TABLE "tasks"."Criticality" IS 'Критичность задач создаваемых в системе';
COMMENT ON COLUMN "tasks"."Criticality"."name" IS 'Название критичности задачи: Basic, Important, Important...';
COMMENT ON COLUMN "tasks"."Criticality"."deadline" IS 'Временной интервал в течение которого ожидается выполнение задачи';
COMMENT ON TABLE "tasks"."Tickets" IS 'Заявки, хранящиеся в системе';
COMMENT ON COLUMN "tasks"."Tickets"."title" IS 'Название задачи в системе';
COMMENT ON COLUMN "tasks"."Tickets"."description" IS 'Описание задачи';
COMMENT ON COLUMN "tasks"."Tickets"."type_id" IS 'Тип задачи';
COMMENT ON COLUMN "tasks"."Tickets"."status_id" IS 'Статус задачи';
COMMENT ON COLUMN "tasks"."Tickets"."criticality_id" IS 'Критичность задачи';
COMMENT ON COLUMN "tasks"."Tickets"."client_id" IS 'Компания-клиент связанная с задачей';
COMMENT ON COLUMN "tasks"."Tickets"."site_id" IS 'Площадка связанная с задачей';
COMMENT ON COLUMN "tasks"."Tickets"."product_id" IS 'Продукт с которым связана проблема';
COMMENT ON COLUMN "tasks"."Tickets"."created_at" IS 'Время создания задачи';
COMMENT ON COLUMN "tasks"."Tickets"."created_by" IS 'Создатель задачи';
COMMENT ON COLUMN "tasks"."Tickets"."updated_at" IS 'Время последнего обновления задачи';
COMMENT ON COLUMN "tasks"."Tickets"."updated_by" IS 'Последний обновивший задачи';
COMMENT ON COLUMN "tasks"."Tickets"."responsible_id" IS 'Ответственный за задачу';
COMMENT ON TABLE "tasks"."ConnectedTickets" IS 'Связь задач';
COMMENT ON TABLE "tasks"."Comments" IS 'Комментарии, оставленные под задачами';
COMMENT ON COLUMN "tasks"."Comments"."created_by" IS 'Создатель комментария';
COMMENT ON COLUMN "tasks"."Comments"."created_at" IS 'Время создания комментария';
COMMENT ON COLUMN "tasks"."Comments"."updated_at" IS 'Время последнего обновления комментария';
COMMENT ON COLUMN "tasks"."Comments"."contents" IS 'Текст комментария';
COMMENT ON TABLE "tasks"."Reactions" IS 'Реакции';
COMMENT ON COLUMN "tasks"."Reactions"."name" IS 'Наименование реакции';
COMMENT ON COLUMN "tasks"."Reactions"."picture" IS 'Картинка реакции, мелкоформатная';
COMMENT ON TABLE "tasks"."CommentsReactions" IS 'Реакциии на комменты';

-- auth
ALTER TABLE "auth"."RolePermissions" ADD FOREIGN KEY ("role_id") REFERENCES "auth"."Roles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "auth"."RolePermissions" ADD FOREIGN KEY ("permission_id") REFERENCES "auth"."Permissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "auth"."Accounts" ADD FOREIGN KEY ("role_id") REFERENCES "auth"."Roles" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "auth"."Sessions" ADD FOREIGN KEY ("account_id") REFERENCES "auth"."Accounts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- profiles / hrm
ALTER TABLE "profiles"."Profiles" ADD FOREIGN KEY ("account_id") REFERENCES "auth"."Accounts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "hrm"."Employees" ADD FOREIGN KEY ("account_id") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- crm
ALTER TABLE "crm"."Clients" ADD FOREIGN KEY ("ceo_id") REFERENCES "auth"."Accounts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "crm"."Representatives" ADD FOREIGN KEY ("account_id") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "crm"."Representatives" ADD FOREIGN KEY ("client_id") REFERENCES "crm"."Clients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "crm"."Sites" ADD FOREIGN KEY ("responsible_id") REFERENCES "crm"."Representatives" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "crm"."SitesProducts" ADD FOREIGN KEY ("site_id") REFERENCES "crm"."Sites" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "crm"."SitesProducts" ADD FOREIGN KEY ("product_id") REFERENCES "crm"."Products" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- nri
ALTER TABLE "nri"."ProductEquipment_Types" ADD FOREIGN KEY ("product_id") REFERENCES "crm"."Products" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "nri"."ProductEquipment_Types" ADD FOREIGN KEY ("equipment_type_id") REFERENCES "nri"."Equipment_Types" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "nri"."Equipment" ADD FOREIGN KEY ("type_id") REFERENCES "nri"."Equipment_Types" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "nri"."Equipment" ADD FOREIGN KEY ("site_id") REFERENCES "crm"."Sites" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- tasks
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("type_id") REFERENCES "tasks"."Type" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("status_id") REFERENCES "tasks"."Status" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("criticality_id") REFERENCES "tasks"."Criticality" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("client_id") REFERENCES "crm"."Clients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("site_id") REFERENCES "crm"."Sites" ("id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("product_id") REFERENCES "crm"."Products" ("id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("created_by") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("updated_by") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Tickets" ADD FOREIGN KEY ("responsible_id") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."ConnectedTickets" ADD FOREIGN KEY ("first_task_id") REFERENCES "tasks"."Tickets" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."ConnectedTickets" ADD FOREIGN KEY ("second_task_id") REFERENCES "tasks"."Tickets" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Comments" ADD FOREIGN KEY ("ticket_id") REFERENCES "tasks"."Tickets" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."Comments" ADD FOREIGN KEY ("created_by") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."CommentsReactions" ADD FOREIGN KEY ("comment_id") REFERENCES "tasks"."Comments" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks"."CommentsReactions" ADD FOREIGN KEY ("reaction_id") REFERENCES "tasks"."Reactions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- +goose Down
